# Generated by Django 4.0.2 on 2022-04-12 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itens', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('serie', models.CharField(max_length=30)),
                ('bmp', models.CharField(max_length=30)),
                ('secao_carga', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('status', models.CharField(max_length=2)),
                ('data', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'material',
            },
        ),
    ]
