# Generated by Django 4.0.2 on 2022-04-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=2)),
                ('serie', models.CharField(max_length=30)),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('cpf', models.CharField(max_length=15)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'registro',
            },
        ),
    ]
